import type { WizardSection } from "./types";
import { PROJECT_GUIDE, USERS_GUIDE } from "./writingGuides";

export const WIZARD_CATALOG: WizardSection[] = [
  {
    id: "contexto",
    title: "Cuéntanos de tu proyecto",
    subtitle: "Nada técnico por aquí, solo queremos entender tu idea.",
    ieee830Category: "CONTEXT",
    questions: [
      {
        id: "contexto-pitch",
        writingGuide: PROJECT_GUIDE,
        prompt: "En pocas palabras, ¿de qué se trata tu proyecto?",
        helpText: "Imagina que se lo explicas a un amigo en 30 segundos.",
        placeholder: "Ej: Una app para que mis clientes agenden citas sin llamarme por WhatsApp.",
        kind: "long_text",
        isRequirement: false,
        ieee830Category: "CONTEXT",
      },
      {
        id: "contexto-usuarios",
        writingGuide: USERS_GUIDE,
        prompt: "¿Quién va a usar esto principalmente?",
        helpText: "Puedes mencionar varios tipos de usuario si aplica.",
        placeholder: "Ej: Mis clientes finales y yo como administrador.",
        kind: "long_text",
        isRequirement: false,
        ieee830Category: "CONTEXT",
      },
    ],
  },
  {
    id: "usuario",
    title: "Lo que necesitas como usuario",
    subtitle: "Describe tus necesidades con tus propias palabras, sin pensar en tecnología.",
    ieee830Category: "USER",
    questions: [
      {
        id: "usuario-necesidades",
        prompt: "¿Qué necesitas poder hacer tú (o tus usuarios) con este sistema?",
        helpText: "Escribe una necesidad y pulsa Enter para agregar otra. Elige la importancia de cada una. Ej: 'Quiero ver mis citas del día'.",
        kind: "requirement_list",
        isRequirement: true,
        ieee830Category: "USER",
      },
    ],
  },
  {
    id: "sistema",
    title: "Piezas que debe tener el sistema",
    subtitle: "Cosas con las que el sistema debe poder conectarse o integrarse.",
    ieee830Category: "SYSTEM",
    questions: [
      {
        id: "sistema-integraciones",
        prompt: "¿Hay algo con lo que el sistema deba conectarse?",
        helpText: "Ej: WhatsApp, una pasarela de pagos o tu inventario actual. Agrega cada conexión con Enter o indica que no necesitas ninguna.",
        emptyAnswerLabel: "No necesito integraciones por ahora",
        kind: "requirement_list",
        isRequirement: true,
        ieee830Category: "SYSTEM",
      },
      {
        id: "sistema-dispositivos",
        prompt: "¿Dónde lo van a usar principalmente?",
        kind: "single_choice",
        options: ["Celular", "Computador", "Ambos por igual", "No estoy seguro"],
        isRequirement: false,
        ieee830Category: "SYSTEM",
      },
    ],
  },
  {
    id: "funcional",
    title: "Lo que el sistema debe hacer",
    subtitle: "Las funcionalidades concretas, una por una.",
    ieee830Category: "FUNCTIONAL",
    questions: [
      {
        id: "funcional-caracteristicas",
        prompt: "Lista las funcionalidades principales que necesitas",
        helpText: "Elige las ideas que te sirvan, ajústalas a tu negocio o escribe tus propias funcionalidades. Define la importancia de cada una.",
        suggestions: [
          "Registrar y consultar clientes",
          "Gestionar pedidos y ventas",
          "Controlar inventario de productos",
          "Agendar citas o reservas",
          "Registrar pagos y gastos",
          "Enviar recordatorios y notificaciones",
          "Consultar reportes del negocio",
          "Asignar tareas y hacer seguimiento",
          "Administrar usuarios y permisos",
          "Buscar y filtrar información",
          "Exportar información a Excel o PDF",
          "Guardar y consultar documentos",
        ],
        kind: "requirement_list",
        isRequirement: true,
        ieee830Category: "FUNCTIONAL",
      },
    ],
  },
  {
    id: "no_funcional",
    title: "Cómo debe comportarse el sistema",
    subtitle: "No son funciones, sino cualidades: qué tan rápido, seguro o fácil debe ser.",
    ieee830Category: "NON_FUNCTIONAL",
    questions: [
      {
        id: "nofuncional-cualidades",
        prompt: "¿Qué es importante para ti en cuanto a velocidad, seguridad o facilidad de uso?",
        helpText: "Marca todas las opciones que sean importantes para tu negocio. Puedes elegir varias y dar a cada una su propia importancia.",
        kind: "multiple_choice",
        options: [
          "Que las pantallas carguen rápido",
          "Que funcione bien con una conexión lenta",
          "Que proteja los datos del negocio y de los clientes",
          "Que cada persona vea solo lo que le corresponde según su rol",
          "Que haga copias de seguridad para recuperar la información",
          "Que sea fácil de aprender y usar",
          "Que sea accesible para personas con distintas capacidades",
          "Que esté disponible cuando lo necesitemos",
          "Que siga funcionando bien al crecer el negocio",
          "Que pida confirmación antes de borrar información importante",
        ],
        isRequirement: true,
        ieee830Category: "NON_FUNCTIONAL",
      },
    ],
  },
];
